include: all_lint_rules.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    deprecated_member_use_from_same_package: ignore
    included_file_warning: ignore
    missing_required_param: error
    missing_return: error
    parameter_assignments: warning
    todo: ignore

  exclude:
    - "**.freezed.dart"
    - "**.g.dart"
    - "**.gr.dart"
    - "bin/cache/**"
    - "build/**"
    - "lib/generated_plugin_registrant.dart"
    - "test/.test_coverage.dart"

linter:
  rules:
    always_put_control_body_on_new_line: false
    always_put_required_named_parameters_first: false
    always_specify_types: false
    always_use_package_imports: false
    avoid_annotating_with_dynamic: false
    avoid_classes_with_only_static_members: false
    avoid_final_parameters: false
    avoid_positional_boolean_parameters: false
    avoid_redundant_argument_values: false
    avoid_types_on_closure_parameters: false
    cascade_invocations: false
    diagnostic_describe_all_properties: false
    discarded_futures: false
    flutter_style_todos: false
    lines_longer_than_80_chars: false
    one_member_abstracts: false
    prefer_double_quotes: false
    prefer_expression_function_bodies: false
    prefer_final_parameters: false
    prefer_foreach: false
    public_member_api_docs: false
    sort_constructors_first: false
    unnecessary_final: false
    use_decorated_box: false
    use_if_null_to_convert_nulls_to_bools: false
