name: 🐞 Bug Report
description: Report a bug
labels: ["bug", "needs triage"]
assignees: [charlescyt]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this bug?
      description: Please check if there is an existing issue for this bug before creating a new one.
      options:
        - label: I have searched the [existing issues](https://github.com/charlescyt/pyramid_lint/issues).
          required: true

  - type: textarea
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug you have encountered.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reproduction Steps
      description: Steps or sample code to reproduce the bug.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Information
      description: Add any additontal information that could help us understand the bug better.
