name: 📚 Documentation Update
description: Suggest improvements or clarifications in documentation
labels: ["documentation", "needs triage"]
assignees: [charlescyt]
body:
  - type: textarea
    attributes:
      label: Documentation Update Description
      description: A clear and concise description of the documentation update you would like to see.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Information
      description: Add any additional information that could help us understand the requested documentation update better.
