include: ../../analysis_options.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - test/golden.dart

custom_lint:
  rules:
    - max_lines_for_file:
      max_lines: 300
    - max_lines_for_function:
      max_lines: 200
    - boolean_prefix:
      valid_prefixes: ["at"]
    - avoid_abbreviations_in_doc_comments:
      abbreviations: ["approx."]
    - avoid_returning_widgets:
      ignored_method_names: ['myMethod']
    - max_switch_cases:
      max_cases: 5
    - prefer_library_prefixes:
      libraries: ["dart:io"]
