name: Build

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build.yml"
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"
      - "analysis_options.yaml"

  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/build.yml"
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"
      - "analysis_options.yaml"

  schedule:
    - cron: "0 13 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Git Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install Dart SDK
        uses: dart-lang/setup-dart@65eb853c7ba17dde3be364c3d2858773e7144260 # v1.7.2

      - name: Show Dart SDK version
        run: dart --version

      - name: Install Dependencies
        run: dart pub get

      - name: Show outdated packages
        run: dart pub outdated

      - name: Check formating
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze
        run: dart analyze

      - name: Run tests
        run: dart test
